### ISSUE TITLE
Styles and Shady DOM

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-jsoneditor#5] opened 2015-09-22 13:47 UTC
There are issues related to Shady DOM, if we are going to support it (see https://github.com/Polyjuice/starcounter-debug-aid/issues/35), we could find nice way to inject styles.

**Comment by miyconst** [comment] 2015-09-22 14:00
The problem is that Polymer scopes the styles imported inside shady dom, and the dom of json editor is created by third party library, which does not add scope classes.

There was a `no-shim` property in Polymer 0.5, which does not seem to work in Polymer 1.x: https://www.polymer-project.org/0.5/docs/polymer/styling.html

We could manually import styles with javascript to avoid the scoping.

Right now the styles are imported like: 
```html
<link rel="import" type="css" href="../../jsoneditor/dist/jsoneditor.min.css">
```
https://www.polymer-project.org/1.0/docs/devguide/styling.html#external-stylesheets

**Comment by warpech** [comment] 2015-10-12 14:09
Looks really bad with default Polymer:

<img width="1053" alt="screenshot 2015-10-12 14 19 56" src="https://cloud.githubusercontent.com/assets/566463/10429683/a1a85c0c-70fa-11e5-8219-01421ee718ab.png">

I guess the easiest solution is to put `<link rel="stylesheet">` to `<head>` using JavaScript. I guess this is what @miyconst proposed.

**Comment by miyconst** [comment] 2015-10-21 08:51
Fixed and released as [1.0.3](https://github.com/Juicy/juicy-jsoneditor/releases/tag/1.0.3).
Now the [demo](http://juicy.github.io/juicy-jsoneditor/) works in all browsers (Chrome, IE, FF).

The jsoneditor styles are being injected to `head` only if Shadow DOM is not enabled.

To make it work in Shady DOM I removed `markdown-body` class from the parent container and wrapped text blocks with `<div class="markdown-body">`, otherwise GitHub styles destroy jsoneditor.

**Closed by miyconst** 2015-10-21 08:51 UTC

**Comment by warpech** [comment] 2015-10-21 10:01
Nice!

--
Marcin Warpechowski
+48 603 607 801

**Comment by yveslange** [comment] 2018-05-23 08:22
Hi,

How can I change the blue color that appears on the header and the borders ?

**Comment by tomalec** [comment] 2018-05-23 10:58
Currently, there is no easy straight forward CSS selector to do that. As the header is inside Shadow DOM, and shadow piercing selectors were deprecated. In long term future we may consider [shadow dom parts](https://meowni.ca/posts/part-theme-explainer/) 

For now, you can try to use imperative API, like:

```html
  <juicy-jsoneditor id="editor"></juicy-jsoneditor>
  <style id="customStyle">
    div.jsoneditor-menu{
        background-color: lightgreen;
        border-color: lightgreen;
    }
    div.jsoneditor{
        border-color: lightgreen;
    }
  </style>
  <script>
    editor.injectTheme('#customStyle');
  </script>
```
See working example at https://jsbin.com/cahiluq/edit?html,output

Alternatively, we could try to implement the feature as in https://github.com/Juicy/juicy-ace-editor#attributes, so you would be able to do the same trick but slightly shorter:
```html
  <style id="customStyle">
    div.jsoneditor-menu{
        background-color: lightgreen;
        border-color: lightgreen;
    }
    div.jsoneditor{
        border-color: lightgreen;
    }
  </style>
  <juicy-jsoneditor shadow-style="#customStyle"></juicy-jsoneditor>
```

Does this meet your need? If not please provide your use case, preferably in the new issue :)
